### ISSUE TITLE
Hotel Class.

### ISSUE THREAD

**Issue by HamzaAnis** [muhammadumerfarooq/Asg1-Hotel-Reservation-System-#3]
The hotel class is missing in the project.

**Comment by muhammadumerfarooq** [comment]
hotel class is not missing, this is the main code or the menu code because i have use class libraries so here the link to main code where the whole logic is build 
https://github.com/muhammadumerfarooq/-Hotel-Reservation-Class-Librares

**Comment by HamzaAnis** [comment]
It was wise to add both of the libraries and main .cs file in the same repository or mention about it in the description. It would be a good practice.

**Comment by muhammadumerfarooq** [comment]
i will keep that in mind in next time

**Comment by HamzaAnis** [comment]
Keep it up. Good work

**Comment by muhammadumerfarooq** [comment]
thanks
😊
